### PR TITLE
Adding reflective boundaries

### PR DESCRIPTION
**Pull request by nicolasmerino41**
Open this PR to implement reflective boundaries so individuals don't have to either disappear at the edges or move towards the other side of the grid. For now, I've updated boundaries.jl and introduced:
```
@inline function DG._inbounds(::Reflect, size::Number, i::Number)
    if i < oneunit(i)
        return 2 - i, true
    elseif i > size
        return 2*size - i, true
    else
        return i, true
    end
end
```
I've now noticed that boundaries.jl from the dev branch does not define _updateboundary!
so I'm not sure the approach I mentioned in issue #249 would work anymore.

### CODE REVIEW

**Comment by rafaqz** [comment]
Oh right. Maybe this is all in Stencils.jl now?

**Comment by rafaqz** [comment]
Ok update_boundary is here:

https://github.com/rafaqz/Stencils.jl/blob/23ce14cd3a3a3daf5deae6bb2f4e57a9716761e3/src/array.jl#L146

And all the boundary conditions live here:
https://github.com/rafaqz/Stencils.jl/blob/main/src/boundary.jl

Best to always refer to `dev` and Stencils.jl, as a lot has changed. Extracting Stencils.jl was a big part of the work the last 2 years... so it can be used for e.g. image/geo morphology, slope filters etc as its like 10x faster than the alternatives and was kind of wasted as the internals of a modelling package.

**Comment by rafaqz** [comment]
I think we need both the Stencils and DynamicGrids PRs - Stencils only handles the window/halo dynamic not the long distance jump rules.

**Comment by nicolasmerino41** [comment]
Ok, so I understand this part would go to DG:
```
 @inline function DG._inbounds(::Reflect, size::Number, i::Number)
    if i < oneunit(i)
        return 2 - i, true
    elseif i > size
        return 2*size - i, true
    else
        return i, true
    end
end
```
While this would go to Stencils.jl:
```
struct Reflect <: BoundaryCondition end

function _updateboundary!(g::DG.GridData{S,R}, ::Reflect) where {S<:Tuple{Y,X},R} where {Y,X}
    src = parent(source(g))
    #  Mirror the adjacent values
    # Left boundary
    @inbounds for i in 1:R
        src[:, i] = src[:, R + 1 - i]
    end
    # Right boundary
    @inbounds for i in 1:R
        src[:, end - i + 1] = src[:, end - R - i]
    end
    # Top boundary
    @inbounds for i in 1:R
        src[i, :] = src[R + 1 - i, :]
    end
    # Bottom boundary
    @inbounds for i in 1:R
        src[end - i + 1, :] = src[end - R - i, :]
    end
end

function _update_padval(::Reflect, ::Any)
    # No operation needed for a reflective, right?
    Reflect()
end
```
I'll make the Stencils PR

**Comment by nicolasmerino41** [comment]
I have not been using long distance jump rules so I'm not sure if that would require any additional implementation.

**Comment by rafaqz** [comment]
That looks like it! Now the trick will be to write a few tests to check that it works.

**Comment by nicolasmerino41** [comment]
Ok. I think everything is done here but it will not work until Reflect() implementation in Stencils is done. I created a test for Reflect but I assume all tests will not pass here regardless, right? They didn't even passed for me before changing anything.

**Comment by nicolasmerino41** [comment]
Ok, so I made some minor changes and the package works perfectly now. I actually used it with my new local Stencils and this code:
```
init = fill(0.0, 10, 10)
init[2,2] = 10000.0
rule = InwardsDispersal{}(
    formulation=ExponentialKernel(λ = 0.125),
    distancemethod=AreaToArea(30)
)
ruleset = Ruleset(rule; boundary=Reflect())
output = ArrayOutput(init; tspan=1:1000)
r = sim!(output, ruleset)
```
has the behaviour we are looking for. Conclusion, I don't know why I don't manage to pass the tests in Stencils but the behaviour is correct. The tests in DG `dev` do not pass either but it throws error even before reaching my actual test so perhaps is not an issue related to this PR?

**Comment by rafaqz** [comment]
Amazing! But yes it will still need a passing test in Stencils.jl

I will try to get the rest of the tests passing again here too.

**Comment by rafaqz** [comment]
I've tagged a new Stencils.jl version. I'll hopefully be able to get the other tests here passing over the weekend so we can merge this too - but apologies I'm too busy the next 2 days.

**Comment by nicolasmerino41** [comment]
Yes, I've noticed, thank you very much! And no worries, fortunately functionality is not affected so I'm already using it in my local :)

Ps: I'm now working on bumping compat versions in GrowthMaps, hopefully you'll get a PR there sooner than later.

**Comment by nicolasmerino41** [comment]
Hey there again :)

One thing before you do the PR. I've been working with the new Reflect() and I've noticed something weird. When you run `Ruleset(init; boundary = Wrap() or Reflect())` on a square matrix, it works fine. But if you do a mask, it doesn't, and you lose a considerable amount of individuals. The fact it doesn't work on Wrap() either shows that it's gotta be related with how neighbors are identified when they're a mask?

Here you have a MWE in case you wanna see it yourself.
```
DA_trial = DimArray(reshape(rand(10.0:100.0, 100*100), 100, 100), (Dim{:a}(1:100), Dim{:b}(1:100)))
DA_mask = trues(dims(DA_trial))
for col in 1:20, row in 1:20 # Generate a random mask with a few falses
    DA_mask[row, col] = false
end

indisp = InwardsDispersal(;
    formulation=ExponentialKernel(λ = 0.125)
)

out = ArrayOutput(DA_trial; tspan=1:100, mask = DA_mask) 
r = sim!(out, Ruleset(indisp; boundary=Wrap()))
sum(r[1])
sum(r[100])
```
You can see the final sum is far from the initial one. I personally do not know what part of the package can the issue arise from, so let me know how you wanna proceed.

Cheers,
Nico

**Comment by rafaqz** [comment]
I think that's because your `init` has some values in the masked area? The first frame `r[1]` is the `init` values, unchanged. `r[2]` will have most of the change already, just from the first application of the mask.

This behavior may or may not make sense, its a fairly arbitrary decision. We could also apply the mask to `init` if you think that is better. ( I think with my data the mask is nearly always made _from_ the init, like with `Rasters.boolmask` or like `mask = init .!= 0`)

I added the fix here:
```julia
DA_trial = DimArray(reshape(rand(10.0:100.0, 100*100), 100, 100), (Dim{:a}(1:100), Dim{:b}(1:100)))
DA_mask = trues(dims(DA_trial))
for col in 1:20, row in 1:20 # Generate a random mask with a few falses
    DA_mask[row, col] = false
end
# Here mask the trial first
DA_trial .*= DA_mask

indisp = InwardsDispersal(;
    formulation=ExponentialKernel(λ = 0.125)
)

out = ArrayOutput(DA_trial; tspan=1:100, mask = DA_mask) 
r = sim!(out, Ruleset(indisp; boundary=Wrap()))
sum(r[1])
sum(r[100])
```

~~There will still be a small change after that no matter what, there is a lot of floating point error across 100 steps of a simulation~~

Edit: now that I think about it, inwards dispersal is a very simple function that doesn't check loss to masked pixels. That will be the reason for the small remaining change in values after you fix your `init` Dispersal.jl was written for insects so we mostly assumed there were actually real losses to mask areas because they do just fly/get blown into the sea and uninhabitable areas quite often. Of course smarter animals wont do that.

`OutwardsDispersal` is more accurate as it actually tracks both directions instead of just running a dot product kernel. But it can be quite a bit slower. 

(There is a potential optimisation to get around that, that I haven't gotten around to writing... it add/substracts values from a small moving window rather than from the main array, updating only one row at a time. We can use a `StaticArrays.MArray` for that, which should be really fast.)

**Comment by nicolasmerino41** [comment]
Thanks for the answer,

I guess it was not the best MWE. My actual grids are already empty on unreachable areas so it's basically like your trick `DA_trial .*= DA_mask`. The thing is that losses are still acceptable with a fairly simple mask like the one in my MWE (because it's just removing a corner), but more complex mask shapes like a more realistic landscape start adding a lot of error. You can see here:
```
# A DimArray of 300 by 300 and fill it with 100.0
DA_300 = DimArray(ones(300, 300) .* 100.0, (Dim{:a}(1:300), Dim{:b}(1:300)))
# A random mask with 80% trues
DA_300_mask = DimArray(rand(Bernoulli(0.8), 300, 300), (Dim{:a}(1:300), Dim{:b}(1:300)))
DA_300 .*= DA_300_mask
out = ArrayOutput(DA_300; tspan=1:100, mask = DA_300_mask) 
r = sim!(out, Ruleset(indisp; boundary=Wrap()))
sum(r[100])/sum(r[1])
```
This is already a 3% loss which is quite a lot for some applications, and I get errors larger than that too. 

Outwards dispersal might not be my best approach cause I need to maintain high efficiencies, so I'll think about the small moving window idea, thanks for the tip.

Cheers,
Nico

**Comment by rafaqz** [comment]
I mean, OutwardsDispersal is still pretty fast compared to any other package that does anything like this... Think 2 orders of magnitude faster rather than 3.

So benchmark before you write more code. The moving window will require pretty gnarly generated functions, to be faster than it is now.

Additionally, make sure OutwardsDispersal actually has a check for masked values, I don't think it does. But it easily could check `mask(data)[I]` in its loop and skip some cells. That will be expensive but you need it. So you should copy that rule and customise it. Or we could add an option for it to check the mask values (I rarely end up using those simple Dispersal.jl rules in practice).

For understanding performance, InwardsDispersal is basically a convolution, which is just dot products over static arrays - which are crazy fast. 
But the math of a convolution can't work out where there are masked cells in the grid. 
So there is no way to match InwardsDispersal and get the accuracy you want with masks. 

With one caveat, if your simulation is very sparse then SpareseOpt and OutwardsDispersal can actually beat InwardsDispersal.

**Comment by rafaqz** [comment]
For this PR, you will want to rebase/merge `dev` to get the latest fixes so the tests pass.

I think your `mask` issues are not related to Reflect specifically, so we can merge?

**Comment by nicolasmerino41** [comment]
Yes, not related to this PR so let's do it :)

**Comment by rafaqz** [comment]
Did you pull and merge/rebase the latest from `dev` here? The erorrs in CI still showing in this PR are fixed here now, see
https://github.com/cesaraustralia/DynamicGrids.jl/actions/runs/9437806052/job/25994099279

**Comment by nicolasmerino41** [comment]
Well, I rebased the upstream dev branch you had updated (I saw your changes implemented) but I did notice the tests did not pass. I'll check it out when I reach my laptop, perhaps I didn't do it correctly :(

**Comment by rafaqz** [comment]
I mess up a rebase at least once a day, that's exoected

**Comment by nicolasmerino41** [comment]
Well, it looks like it's all good now. For some reason the rebase updated everything but the Project.toml

Have a great day :)

**Comment by rafaqz** [comment]
Thanks, its really nice to have someone moving this package along with PRs

**Pull request merged**
